# Generated by Django 4.1.5 on 2023-01-15 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
