# Generated by Django 4.1.5 on 2023-01-16 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0017_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
