# Generated by Django 4.1.5 on 2023-01-18 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0019_hero'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
